In [1]:
# Slides for Probability and Statistics module, 2016-2017
# Matt Watkins, University of Lincoln

## Types of Marokov Chain

there are actually several types of Markov chain that can be categorized by the properties of their transition matrices. Their properties are qualitatively different in the long term.

We'll only look at

- Absorbing chains
- Ergodic Chains
    - Regular Chains
    

## Absorbing Markov Chains

**definition**

a Markov Chain is called absorbing if it has at least one state $s_i$ that is impossible to leave, $p_{ii} = 1$, and it is possible to reach an absorbing state from every state.

**definition**

states with $p_{ii} = 1$ are called absorbing states. Other states are called _transient states_.



**Example**

A man walks along a four-block stretch of Park Avenue.  

If he is at corner 1, 2, or 3, then he walks to the left or right with equal
probability.

He continues until he reaches corner 4, which is a bar, or corner 0, which is his home.  

If he reaches either home or the bar, he stays there.

![](PSfig11-3.png)


We form a Markov chain with states 0, 1, 2, 3, and 4.  States 0 and 4 are
absorbing states.  

The transition matrix is then

$$
\textbf{P} =\begin{matrix}
  &  0  &  1  &  2  &  3  &  4  \cr
0 &  1  &  0  &  0  &  0  &  0  \cr
1 & 1/2 &  0  & 1/2 &  0  &  0  \cr
2 &  0  & 1/2 &  0  & 1/2 &  0  \cr
3 &  0  &  0  & 1/2 &  0  & 1/2 \cr
4 &  0  &  0  &  0  &  0  &  1 \cr \end{matrix}
$$
The states 1, 2, and 3 are transient states, and from any of these
it is possible to reach the absorbing states 0 and 4.  

The chain is an absorbing chain.  When a process reaches an absorbing state, we shall say that
it is absorbed.


# Markov Chain diagrams

it can be useful to depict a Markov Chain in diagramatic form. 

For instance for the Drunkard's walk we had

![](PSfig11-3.png)

the nodes show the states, $s_j$, whilst the arrows show the transition probabilities, $p_{ij}$. 

The diagrams make it easy to spot absorbing states, here the two end states, which have no arrows heading back to other states.

## Visual picture

you can make these diagrams prettier

[visiualization of Markov Chains](http://setosa.io/ev/markov-chains/)


**example**

example of an absorbing Markov chain

![](https://s-media-cache-ak0.pinimg.com/736x/03/c3/ab/03c3ab693eedcd84c1119a947974cb93.jpg)

The 100 is absorbing (in the sense the game ends at that point). The other tiles are transient states.

It is quite possible to set up and solve this, finding the tiles that most time is spent on etc. 

[snakes and ladders analysed](http://www.datagenetics.com/blog/november12011/)


## Canonical Form

If we rearrange the transition matrix for an absorbing chain so that the transient states are first, followed by the absorbing states we get the so called canonical form, which will have the general form

![](absorb_I.png)



and it can be shown that

![](absorb_II.png)

it retains the same block structure when raised to the power $n$. We can extract the answers to the questions from the matrices $\mathbf{Q}$ and $\mathbf{R}$:



- What is the  probability that the process will eventually reach an absorbing state?
- What is the probability that the process will end up in a given absorbing state?
- On the average, how long will it take for the process to be absorbed?
- On the average, how many times will the process be in each transient state?  

The answers to all these questions depend, in general, on the
state from which the process starts as well as the transition probabilities.

## Ergodic Markov Chains

#### definition

A Markov chain is called an ergodic chain if it is possible to go from every state to every state (though this can be in several moves).

#### definition

A Markov chain is called a regular chain if some power of the transition matrix has only positive elements.

Every regular chain is ergodic, but not all ergodic chains are regular.


### Long time behaviour

Regular Markov chains have a well defined long term behaviour

**theorem**
Let $\textbf{P}$ is the transition matrix from a regular chain. Then, as $n \to \infty$, the powers $\textbf{P$^{(n)}$}$ approach a limiting matrix $\textbf{W}$ with all rows the same vector $\textbf{w}$.

If we look at our Land of Oz example we can see this in action

In [6]:
import numpy as np

w = [0.4,0.2,0.4]

P = np.array([[0.5, 0.25,0.25], [0.5, 0.0,0.5],[0.25,0.25,0.5]])
Pn = [[0.4, 0.2,0.4], [0.4, 0.2,0.4],[0.4,0.2,0.4]]

Pi = P

for i in range (1,6):
    Pi = np.dot(P,Pi)
    print("P^",i+1,"=\n",Pi,"\n")

print("wP^n = ", np.dot(w,Pn),"\n")
print("wP = ",np.dot(w,P),"\n")

P^ 2 =
 [[ 0.4375  0.1875  0.375 ]
 [ 0.375   0.25    0.375 ]
 [ 0.375   0.1875  0.4375]] 

P^ 3 =
 [[ 0.40625   0.203125  0.390625]
 [ 0.40625   0.1875    0.40625 ]
 [ 0.390625  0.203125  0.40625 ]] 

P^ 4 =
 [[ 0.40234375  0.19921875  0.3984375 ]
 [ 0.3984375   0.203125    0.3984375 ]
 [ 0.3984375   0.19921875  0.40234375]] 

P^ 5 =
 [[ 0.40039062  0.20019531  0.39941406]
 [ 0.40039062  0.19921875  0.40039062]
 [ 0.39941406  0.20019531  0.40039062]] 

P^ 6 =
 [[ 0.40014648  0.19995117  0.39990234]
 [ 0.39990234  0.20019531  0.39990234]
 [ 0.39990234  0.19995117  0.40014648]] 

wP^n =  [ 0.4  0.2  0.4] 

wP =  [ 0.4  0.2  0.4] 



If this vector $\textbf{w}$ is a steady state of the chain then we should have that $\textbf{w} \textbf{P} = \textbf{w}\lambda$.

In fact we have that $\textbf{w} \textbf{P} = \textbf{wI}$, where $\textbf{I}$ is an identity matrix, because we need to preserve the amount of probability 

We can find $\textbf{w}$ by linear algebra techniques:

- find the eigenvalues/vectors of $\textbf{P}$
- directly solve $\textbf{w} \textbf{P} = \textbf{wI}$, as we know that we want the eigenvector with eigenvalue 1.

## Random Walks

random walks can occur in spaces with various dimensions. The simplest ones work with a fixed step.

We've seen one, in 1D - the difference between the number of heads and tails thrown when a coin is repeatedly tossed

- at each step the walker can move up, with probability $p$, or down, with probability $1-p$ the number line

In 2D (on a regular grid)

- at each step the walker can move to one of the eight neighbouring sites

In 3D (on a regular grid) we have something rather similar to diffusion

- at each step the walker can move to one of the 9 + 8 + 9 = 26 neighbouring sites

Interestingly, there are qualitative differences between the walks in 1 and 2 or 3 dimensions.

- It can be proved that in 1 or 2 D the walker will always return to its starting point.
- In 3D the walker may never return (probability of return is approximately only 1/3)

Grinstead and Snell sum this up as

>"One may summarize these results by stating that one should not get drunk in more than two dimensions."

# Summary

- describe the evolution between a series of states
- Markov Chains depend on the current state, but not previous history
- Initial state vector defines how the chain starts
- Transition matrix (often called the stochastic matrix) built from  the transition probabilities between states
- evolution occurs by applying the transition matrix repeatedly - each application is a step
- use methods of linear algebra to explore long time properties of the chains